openapi: 3.0.3
servers:
- url: https://dev.xxx.com
  description: Development server
- url: https://prod.xxx.com
  description: Production server
info:
  version: 1.0.0
  title: ECHONET Lite Web APIs
  description: API server with EL Web APIs
  termsOfService: https://xxxx.com/terms/
  contact:
    name: API support
    url: https://xxx.com/support/
    email: support@xxx.com
  license:
    name: MIT License
    url: https://opensource.org/license/mit/
tags:
- name: HumanDetectionSensor
  description: tag for Human detection sensor
security:
- api_key: []
paths:
  /elapi/v1/devices/{device_id}/properties:
    get:
      tags:
      - HumanDetectionSensor
      summary: 'Get: properties'
      operationId: getDevicesPropertiesHumanDetectionSensor
      description: '取得: properties'
      parameters:
      - description: device id
        name: device_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/propertiesHumanDetectionSensor'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /elapi/v1/devices/{device_id}/properties/thresholdLevel:
    get:
      tags:
      - HumanDetectionSensor
      summary: 'Get: Detection threshold level'
      operationId: getDevicesPropertiesThresholdLevelHumanDetectionSensor
      description: '取得: 検知閾値レベル設定'
      parameters:
      - description: device id
        name: device_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/thresholdLevelHumanDetectionSensor'
        '401':
          $ref: '#/components/responses/Unauthorized'
    put:
      tags:
      - HumanDetectionSensor
      summary: 'Set: Detection threshold level'
      operationId: putDevicesPropertiesThresholdLevelHumanDetectionSensor
      description: '設定: 検知閾値レベル設定'
      parameters:
      - description: device id
        name: device_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/thresholdLevelHumanDetectionSensor'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/thresholdLevelHumanDetectionSensor'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /elapi/v1/devices/{device_id}/properties/detection:
    get:
      tags:
      - HumanDetectionSensor
      summary: 'Get: Human detection status'
      operationId: getDevicesPropertiesDetectionHumanDetectionSensor
      description: '取得: 人体検知状態'
      parameters:
      - description: device id
        name: device_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/detectionHumanDetectionSensor'
        '401':
          $ref: '#/components/responses/Unauthorized'
components:
  schemas:
    Error:
      description: error with type and message
      type: object
      properties:
        type:
          type: string
        message:
          type: string
    propertiesHumanDetectionSensor:
      description: propertiesHumanDetectionSensor
      type: object
      properties:
        thresholdLevel:
          type: number
          minimum: 1
          maximum: 8
          multipleOf: 1
          description: '[ja: 検知閾値レベル設定, en: Detection threshold level] '
        detection:
          type: boolean
          description: '[ja: 人体検知状態, en: Human detection status] _True (ja: 検知有, en:
            Detected) False (ja: 検知無, en: Not detected) '
    thresholdLevelHumanDetectionSensor:
      description: '[ja: 検知閾値レベル設定, en: Detection threshold level]'
      type: object
      properties:
        thresholdLevel:
          type: number
          minimum: 1
          maximum: 8
          multipleOf: 1
          description: '[ja: 検知閾値レベル設定, en: Detection threshold level] '
    detectionHumanDetectionSensor:
      description: '[ja: 人体検知状態, en: Human detection status]'
      type: object
      properties:
        detection:
          type: boolean
          description: '[ja: 人体検知状態, en: Human detection status] _True (ja: 検知有, en:
            Detected) False (ja: 検知無, en: Not detected) '
  requestBodies: {}
  responses:
    Unauthorized:
      description: Unauthorized.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: X-Elapi-key
