openapi: 3.0.3
servers:
- url: https://dev.xxx.com
  description: Development server
- url: https://prod.xxx.com
  description: Production server
info:
  version: 1.0.0
  title: ECHONET Lite Web APIs
  description: API server with EL Web APIs
  termsOfService: https://xxxx.com/terms/
  contact:
    name: API support
    url: https://xxx.com/support/
    email: support@xxx.com
  license:
    name: MIT License
    url: https://opensource.org/license/mit/
tags:
- name: HumiditySensor
  description: tag for Humidity sensor
security:
- api_key: []
paths:
  /elapi/v1/devices/{device_id}/properties:
    get:
      tags:
      - HumiditySensor
      summary: 'Get: properties'
      operationId: getDevicesPropertiesHumiditySensor
      description: '取得: properties'
      parameters:
      - description: device id
        name: device_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/propertiesHumiditySensor'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /elapi/v1/devices/{device_id}/properties/value:
    get:
      tags:
      - HumiditySensor
      summary: 'Get: Measured value of relative humidity'
      operationId: getDevicesPropertiesValueHumiditySensor
      description: '取得: 相対湿度計測値'
      parameters:
      - description: device id
        name: device_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/valueHumiditySensor'
        '401':
          $ref: '#/components/responses/Unauthorized'
components:
  schemas:
    Error:
      description: error with type and message
      type: object
      properties:
        type:
          type: string
        message:
          type: string
    propertiesHumiditySensor:
      description: propertiesHumiditySensor
      type: object
      properties:
        value:
          type: number
          minimum: 0
          maximum: 100
          description: '[ja: 相対湿度計測値, en: Measured value of relative humidity] '
    valueHumiditySensor:
      description: '[ja: 相対湿度計測値, en: Measured value of relative humidity]'
      type: object
      properties:
        value:
          type: number
          minimum: 0
          maximum: 100
          description: '[ja: 相対湿度計測値, en: Measured value of relative humidity] '
  requestBodies: {}
  responses:
    Unauthorized:
      description: Unauthorized.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: X-Elapi-key
