openapi: 3.0.3
servers:
- url: https://dev.xxx.com
  description: Development server
- url: https://prod.xxx.com
  description: Production server
info:
  version: 1.0.0
  title: ECHONET Lite Web APIs
  description: API server with EL Web APIs
  termsOfService: https://xxxx.com/terms/
  contact:
    name: API support
    url: https://xxx.com/support/
    email: support@xxx.com
  license:
    name: MIT License
    url: https://opensource.org/license/mit/
tags:
- name: CommercialAirConditionerOutdoorUnit
  description: tag for Package-type commercial air conditioner (outdoor unit)
security:
- api_key: []
paths:
  /elapi/v1/devices/{device_id}/properties:
    get:
      tags:
      - CommercialAirConditionerOutdoorUnit
      summary: 'Get: properties'
      operationId: getDevicesPropertiesCommercialAirConditionerOutdoorUnit
      description: '取得: properties'
      parameters:
      - description: device id
        name: device_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/propertiesCommercialAirConditionerOutdoorUnit'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /elapi/v1/devices/{device_id}/properties/specialState:
    get:
      tags:
      - CommercialAirConditionerOutdoorUnit
      summary: 'Get: Special state'
      operationId: getDevicesPropertiesSpecialStateCommercialAirConditionerOutdoorUnit
      description: '取得: 特殊状態'
      parameters:
      - description: device id
        name: device_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/specialStateCommercialAirConditionerOutdoorUnit'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /elapi/v1/devices/{device_id}/properties/ratedPowerConsumption:
    get:
      tags:
      - CommercialAirConditionerOutdoorUnit
      summary: 'Get: Rated power consumption of outdoor unit'
      operationId: getDevicesPropertiesRatedPowerConsumptionCommercialAirConditionerOutdoorUnit
      description: '取得: 室外機定格消費電力値'
      parameters:
      - description: device id
        name: device_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ratedPowerConsumptionCommercialAirConditionerOutdoorUnit'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /elapi/v1/devices/{device_id}/properties/outdoorTemperature:
    get:
      tags:
      - CommercialAirConditionerOutdoorUnit
      summary: 'Get: Measured outdoor unit temperature'
      operationId: getDevicesPropertiesOutdoorTemperatureCommercialAirConditionerOutdoorUnit
      description: '取得: 室外機温度計測値'
      parameters:
      - description: device id
        name: device_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/outdoorTemperatureCommercialAirConditionerOutdoorUnit'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /elapi/v1/devices/{device_id}/properties/groupInformation:
    get:
      tags:
      - CommercialAirConditionerOutdoorUnit
      summary: 'Get: Group information'
      operationId: getDevicesPropertiesGroupInformationCommercialAirConditionerOutdoorUnit
      description: '取得: グループ情報'
      parameters:
      - description: device id
        name: device_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/groupInformationCommercialAirConditionerOutdoorUnit'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /elapi/v1/devices/{device_id}/properties/powerConsumption:
    get:
      tags:
      - CommercialAirConditionerOutdoorUnit
      summary: 'Get: Measured power consumption of outdoor unit'
      operationId: getDevicesPropertiesPowerConsumptionCommercialAirConditionerOutdoorUnit
      description: '取得: 室外機消費電力計測値'
      parameters:
      - description: device id
        name: device_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/powerConsumptionCommercialAirConditionerOutdoorUnit'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /elapi/v1/devices/{device_id}/properties/powerConsumptionWillBeSaved:
    get:
      tags:
      - CommercialAirConditionerOutdoorUnit
      summary: 'Get: Possible power savings for outdoor units'
      operationId: getDevicesPropertiesPowerConsumptionWillBeSavedCommercialAirConditionerOutdoorUnit
      description: '取得: 室外機節電可能消費電力'
      parameters:
      - description: device id
        name: device_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/powerConsumptionWillBeSavedCommercialAirConditionerOutdoorUnit'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /elapi/v1/devices/{device_id}/properties/powerConsumptionLimit:
    get:
      tags:
      - CommercialAirConditionerOutdoorUnit
      summary: 'Get: Settings restricting power consumption of outdoor units'
      operationId: getDevicesPropertiesPowerConsumptionLimitCommercialAirConditionerOutdoorUnit
      description: '取得: 室外機消費電力制限設定'
      parameters:
      - description: device id
        name: device_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/powerConsumptionLimitCommercialAirConditionerOutdoorUnit'
        '401':
          $ref: '#/components/responses/Unauthorized'
    put:
      tags:
      - CommercialAirConditionerOutdoorUnit
      summary: 'Set: Settings restricting power consumption of outdoor units'
      operationId: putDevicesPropertiesPowerConsumptionLimitCommercialAirConditionerOutdoorUnit
      description: '設定: 室外機消費電力制限設定'
      parameters:
      - description: device id
        name: device_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/powerConsumptionLimitCommercialAirConditionerOutdoorUnit'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/powerConsumptionLimitCommercialAirConditionerOutdoorUnit'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /elapi/v1/devices/{device_id}/properties/restrictedMinimumPowerConsumption:
    get:
      tags:
      - CommercialAirConditionerOutdoorUnit
      summary: 'Get: Minimum power consumption for restricted outdoor unit'
      operationId: getDevicesPropertiesRestrictedMinimumPowerConsumptionCommercialAirConditionerOutdoorUnit
      description: '取得: 室外機抑制最低消費電力'
      parameters:
      - description: device id
        name: device_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/restrictedMinimumPowerConsumptionCommercialAirConditionerOutdoorUnit'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /elapi/v1/devices/{device_id}/properties/groupDeviceList:
    get:
      tags:
      - CommercialAirConditionerOutdoorUnit
      summary: 'Get: List of devices in group'
      operationId: getDevicesPropertiesGroupDeviceListCommercialAirConditionerOutdoorUnit
      description: '取得: グループ内デバイスリスト'
      parameters:
      - description: device id
        name: device_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/groupDeviceListCommercialAirConditionerOutdoorUnit'
        '401':
          $ref: '#/components/responses/Unauthorized'
components:
  schemas:
    Error:
      description: error with type and message
      type: object
      properties:
        type:
          type: string
        message:
          type: string
    propertiesCommercialAirConditionerOutdoorUnit:
      description: propertiesCommercialAirConditionerOutdoorUnit
      type: object
      properties:
        specialState:
          type: boolean
          description: '[ja: 特殊状態, en: Special state] _False (ja: 通常状態, en: Normal
            operation) True (ja: 特殊状態, en: Special state) '
        ratedPowerConsumption:
          type: object
          properties:
            cooling:
              oneOf:
              - type: number
                minimum: 0
                maximum: 4294967293
              - type: string
                enum:
                - unsupported
                description: '_unsupported (ja: 未サポート, en: Unsupported) '
              description: '[ja: 冷房, en: Cooling] _'
            heating:
              oneOf:
              - type: number
                minimum: 0
                maximum: 4294967293
              - type: string
                enum:
                - unsupported
                description: '_unsupported (ja: 未サポート, en: Unsupported) '
              description: '[ja: 暖房, en: Heating] _'
          description: '[ja: 室外機定格消費電力値, en: Rated power consumption of outdoor unit] '
        outdoorTemperature:
          oneOf:
          - type: number
            minimum: -127
            maximum: 125
          - type: string
            enum:
            - unmeasurable
            description: '_unmeasurable (ja: 計測値を返せない, en: When the measurement value
              cannot be returned) '
          description: '[ja: 室外機温度計測値, en: Measured outdoor unit temperature] '
        groupInformation:
          oneOf:
          - type: number
            minimum: 1
            maximum: 253
          - type: string
            enum:
            - noSetting
            description: '_noSetting (ja: 設定なし, en: No setting) '
          description: '[ja: グループ情報, en: Group information] '
        powerConsumption:
          type: number
          minimum: 0
          maximum: 4294967293
          description: '[ja: 室外機消費電力計測値, en: Measured power consumption of outdoor
            unit] '
        powerConsumptionWillBeSaved:
          type: number
          minimum: 0
          maximum: 4294967293
          description: '[ja: 室外機節電可能消費電力, en: Possible power savings for outdoor units] '
        powerConsumptionLimit:
          oneOf:
          - type: number
            minimum: 1
            maximum: 4294967293
          - type: string
            enum:
            - canceling
            description: '_canceling (ja: 電力制限解除, en: Canceling the restriction) '
          description: '[ja: 室外機消費電力制限設定, en: Settings restricting power consumption
            of outdoor units] '
        restrictedMinimumPowerConsumption:
          type: number
          minimum: 0
          maximum: 4294967293
          description: '[ja: 室外機抑制最低消費電力, en: Minimum power consumption for restricted
            outdoor unit] '
        groupDeviceList:
          type: array
          items:
            type: object
            properties:
              deviceId:
                type: string
              deviceType:
                type: string
          description: '[ja: グループ内デバイスリスト, en: List of devices in group] '
    specialStateCommercialAirConditionerOutdoorUnit:
      description: '[ja: 特殊状態, en: Special state]'
      type: object
      properties:
        specialState:
          type: boolean
          description: '[ja: 特殊状態, en: Special state] _False (ja: 通常状態, en: Normal
            operation) True (ja: 特殊状態, en: Special state) '
    ratedPowerConsumptionCommercialAirConditionerOutdoorUnit:
      description: '[ja: 室外機定格消費電力値, en: Rated power consumption of outdoor unit]'
      type: object
      properties:
        ratedPowerConsumption:
          type: object
          properties:
            cooling:
              oneOf:
              - type: number
                minimum: 0
                maximum: 4294967293
              - type: string
                enum:
                - unsupported
                description: '_unsupported (ja: 未サポート, en: Unsupported) '
              description: '[ja: 冷房, en: Cooling] _'
            heating:
              oneOf:
              - type: number
                minimum: 0
                maximum: 4294967293
              - type: string
                enum:
                - unsupported
                description: '_unsupported (ja: 未サポート, en: Unsupported) '
              description: '[ja: 暖房, en: Heating] _'
          description: '[ja: 室外機定格消費電力値, en: Rated power consumption of outdoor unit] '
    outdoorTemperatureCommercialAirConditionerOutdoorUnit:
      description: '[ja: 室外機温度計測値, en: Measured outdoor unit temperature]'
      type: object
      properties:
        outdoorTemperature:
          oneOf:
          - type: number
            minimum: -127
            maximum: 125
          - type: string
            enum:
            - unmeasurable
            description: '_unmeasurable (ja: 計測値を返せない, en: When the measurement value
              cannot be returned) '
          description: '[ja: 室外機温度計測値, en: Measured outdoor unit temperature] '
    groupInformationCommercialAirConditionerOutdoorUnit:
      description: '[ja: グループ情報, en: Group information]'
      type: object
      properties:
        groupInformation:
          oneOf:
          - type: number
            minimum: 1
            maximum: 253
          - type: string
            enum:
            - noSetting
            description: '_noSetting (ja: 設定なし, en: No setting) '
          description: '[ja: グループ情報, en: Group information] '
    powerConsumptionCommercialAirConditionerOutdoorUnit:
      description: '[ja: 室外機消費電力計測値, en: Measured power consumption of outdoor unit]'
      type: object
      properties:
        powerConsumption:
          type: number
          minimum: 0
          maximum: 4294967293
          description: '[ja: 室外機消費電力計測値, en: Measured power consumption of outdoor
            unit] '
    powerConsumptionWillBeSavedCommercialAirConditionerOutdoorUnit:
      description: '[ja: 室外機節電可能消費電力, en: Possible power savings for outdoor units]'
      type: object
      properties:
        powerConsumptionWillBeSaved:
          type: number
          minimum: 0
          maximum: 4294967293
          description: '[ja: 室外機節電可能消費電力, en: Possible power savings for outdoor units] '
    powerConsumptionLimitCommercialAirConditionerOutdoorUnit:
      description: '[ja: 室外機消費電力制限設定, en: Settings restricting power consumption of
        outdoor units]'
      type: object
      properties:
        powerConsumptionLimit:
          oneOf:
          - type: number
            minimum: 1
            maximum: 4294967293
          - type: string
            enum:
            - canceling
            description: '_canceling (ja: 電力制限解除, en: Canceling the restriction) '
          description: '[ja: 室外機消費電力制限設定, en: Settings restricting power consumption
            of outdoor units] '
    restrictedMinimumPowerConsumptionCommercialAirConditionerOutdoorUnit:
      description: '[ja: 室外機抑制最低消費電力, en: Minimum power consumption for restricted
        outdoor unit]'
      type: object
      properties:
        restrictedMinimumPowerConsumption:
          type: number
          minimum: 0
          maximum: 4294967293
          description: '[ja: 室外機抑制最低消費電力, en: Minimum power consumption for restricted
            outdoor unit] '
    groupDeviceListCommercialAirConditionerOutdoorUnit:
      description: '[ja: グループ内デバイスリスト, en: List of devices in group]'
      type: object
      properties:
        groupDeviceList:
          type: array
          items:
            type: object
            properties:
              deviceId:
                type: string
              deviceType:
                type: string
          description: '[ja: グループ内デバイスリスト, en: List of devices in group] '
  requestBodies: {}
  responses:
    Unauthorized:
      description: Unauthorized.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: X-Elapi-key
